bboard/urls.py
from django.urls import path

from .views import index, BbByRubricView,nologin, BbDetailView,BbAddView,BbEditView,BbDeleteView,BbIndexView

app_name='bboard'
urlpatterns = [
    path('add/', BbAddView.as_view(), name='add'),
    path('nologin/', nologin, name='nologin'),
    # path('day/', BbIndexView.as_view(), name='day'),
    path('edit/<int:pk>/', BbEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),
    path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),
    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),


    path('', index, name='index'),
]

django3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('bboard/', include('bboard.urls')),
    path('admin/', admin.site.urls),
]

bboard/models.py
from django.db import models


class Bb(models.Model):

    title = models.CharField(max_length=50, verbose_name='Товар', default='Какой-то товар')
    # slug = models.SlugField(max_length=50, unique_for_date='publish')
    content = models.TextField(null=True, blank=True, verbose_name='Описание')
    price = models.FloatField(null=True, blank=True, verbose_name='Цена', help_text='руб.')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано', help_text='Дата и время публикации товара')

    rubric=models.ForeignKey('Rubric', null=True, on_delete=models.PROTECT, verbose_name='Рубрика')



    class Meta:
        verbose_name_plural='Объявления'
        verbose_name='Объявление'
        ordering=['-published']

class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural='Рубрики'
        verbose_name='Рубрика'
        ordering=['name']

bboard/forms.py
from django.forms import modelform_factory, DecimalField, ModelForm
from django import forms
from django.forms.widgets import Select

from .models import Bb,Rubric


class BbForm(ModelForm):
    price = forms.DecimalField(label='Цена!',decimal_places=2)
    rubric=forms.ModelChoiceField(queryset=Rubric.objects.all(),
                                  label='Рубрика!', help_text='Задайте рубрику',
                                  widget=forms.widgets.Select(attrs={'size':4}),empty_label='ХАЛВА')
    title=forms.CharField(label='Название продукта', label_suffix=':', initial='вводи здесь')




    class Meta:
        model=Bb
        fields=('title','content', 'price', 'rubric')
        labels = {'title': 'Название товара'}




# class BbForm(ModelForm):
#     class Meta:
#         model=Bb
#         fields=('title','content', 'price', 'rubric')
#         labels = {'title': 'Название товара'}
#         help_texts={'rubric':'Не забудьте выбрать рубрику'}
#         field_classes={'price':DecimalField}
#         widgets={'rubric':Select(attrs={'size':8})}

# BbForm = modelform_factory(Bb,fields=('title','content','price','rubric'),
#                            labels={'title':'Название товара'},
#                            help_texts={'rubric':'Не забудьте выбрать рубрику'},
#                            field_classes={'price':DecimalField},
#                            widgets={'rubric':Select(attrs={'size':8})})

bboard/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView,FormView,UpdateView,DeleteView
from django.views.generic.dates import ArchiveIndexView
from .models import Bb, Rubric

from .forms import BbForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



# class BbCreateView(CreateView):
#     template_name = 'bboard/create.html'
#     form_class = BbForm
#     success_url = reverse_lazy('index')
#     def get_context_data(self, **kwargs):
#         context=super().get_context_data(**kwargs)
#         context['rubrics']=Rubric.objects.all()
#         return context

# def by_rubric(request,rubric_id):
#     bbs=Bb.objects.filter(rubric=rubric_id)
#     rubrics=Rubric.objects.all()
#     current_rubric=Rubric.objects.get(pk=rubric_id)
#     context={'bbs':bbs, 'rubrics':rubrics, 'current_rubric':current_rubric}
#     return render(request, 'bboard/by_rubric.html', context)

# class BbByRubricView(TemplateView):
#     template_name = 'bboard/by_rubric.html'
#
#     def get_context_data(self, **kwargs):
#         context=super().get_context_data(**kwargs)
#         context['bbs']=Bb.objects.filter(rubric=context['rubric_id'])
#         context['rubrics']=Rubric.objects.all()
#         context['current_rubric']=Rubric.objects.get(pk=context['rubric_id'])
#         return context

class BbByRubricView(ListView):
    template_name = 'bboard/by_rubric.html'
    context_object_name = 'bbs'

    def get_queryset(self):
        return Bb.objects.filter(rubric=self.kwargs['rubric_id'])

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        # context['bbs']=Bb.objects.filter(rubric=context['rubric_id'])
        context['rubrics']=Rubric.objects.all()
        context['current_rubric']=Rubric.objects.get(pk=self.kwargs['rubric_id'])
        return context



def index(request):
    bbs = Bb.objects.all()
    rubrics=Rubric.objects.all()
    paginator=Paginator(bbs,2)
    if 'page' in request.GET:
        page_num=request.GET['page']
    else:
        page_num=1
    page=paginator.get_page(page_num)
    context={'rubrics':rubrics, 'page':page,'bbs':page.object_list }

    return render(request, 'bboard/index.html', context)

def nologin(request):

    return render(request, 'bboard/nologin.html')

# def add(request):
#     bbf=BbForm()
#     context={'form':bbf}
#     return render(request,'bboard/create.html',context)
# def add_save(request):
#     bbf=BbForm(request.POST)
#     if bbf.is_valid():
#         bbf.save()
#         return HttpResponseRedirect(reverse('by_rubric',kwargs={'rubric_id':bbf.cleaned_data['rubric'].pk}))
#     else:
#         context={'form':bbf}
#         return render(request,'bboard/create.html',context)
# @login_required
# def add_and_save(request):
#     if request.method=='POST':
#         bbf = BbForm(request.POST)
#         if bbf.is_valid():
#             bbf.save()
#             return HttpResponseRedirect(reverse('bboard:by_rubric',kwargs={'rubric_id':bbf.cleaned_data['rubric'].pk}))
#         else:
#             context = {'form': bbf}
#             return render(request, 'bboard/create.html', context)
#     else:
#         bbf = BbForm()
#         context = {'form': bbf}
#         return render(request, 'bboard/create.html', context)

class BbDetailView(DetailView):
    model = Bb

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['rubrics']=Rubric.objects.all()
        return context

class BbAddView(LoginRequiredMixin,FormView):
    template_name = 'bboard/create.html'
    form_class = BbForm
    initial = {'price':0.0}

    def get_context_data(self, *args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        context['rubrics']=Rubric.objects.all()
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        self.object=super().get_form(form_class)
        return self.object

    def get_success_url(self):
        return reverse('bboard:by_rubric', kwargs={'rubric_id':self.object.cleaned_data['rubric'].pk})


class BbEditView(LoginRequiredMixin,UpdateView):
    model = Bb
    form_class = BbForm
    success_url = reverse_lazy('bboard:index')

    def get_context_data(self,*args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        context['rubrics']=Rubric.objects.all()
        return context

class BbDeleteView(LoginRequiredMixin,DeleteView):
    model = Bb
    success_url = reverse_lazy('bboard:index')

    def get_context_data(self, *args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        context['rubrics']=Rubric.objects.all()
        return context

class BbIndexView(ArchiveIndexView):
    model = Bb
    date_field = 'published'
    date_list_period = 'day'
    template_name = 'bboard/index.html'
    context_object_name = 'bbs'
    allow_empty = True

    def get_context_data(self, *args, **kwargs):
        context=super().get_context_data(*args,**kwargs)
        context['rubrics']=Rubric.objects.all()
        return context

# def edit(request, pk):
    # bb=Bb.objects.get(pk=pk)
    # if request.mathod=='POST':
    #     bbf=BbForm(request.POST,instance=bb)
    #     if bbf.is_valid:
    #         if bbf.has_changed():
    #             bbf.save()
    #             return HttpResponseRedirect(reverse('bboard:by_rubric',kwargs={'rubric_id':bbf.cleaned_data['rubric'].pk}))
    #     else:
    #         context={'form':bbf}
    #         return render(request,'bboard/bb_form.html',context)
    # else:
    #     bbf=BbForm(instance=bb)
    #     context={'form':bbf}
    #     return render(request,'bboard/bb_form.html',context)

bboard/templates/bboard/bb_archive.html
{% extends "layout/basic.html" %}
{% block content %}

    <p>
            {% for d in date_list %}
                {{ d.published }}
            {% endfor %}
        </p>
{% endblock %}

bboard/templates/bboard/bb_confirm_delete.html
{% extends "layout/basic.html" %}
{% block title %}Удаление объявления{% endblock %}

{% block content %}
<h2>Удаление объявления</h2>
<p>Рубрика: {{ bb.rubric.name }}</p>
    <p>Товар: {{ bb.title }}</p>
    <p>{{ bb.content }}</p>
    <p>Цена: {{ bb.price }}</p>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
</form>
{% endblock %}

bboard/templates/bboard/bb_detail.html
{% extends "layout/basic.html" %}

{% block title %}{{ bb.title }}{% endblock %}

{% block content %}


    <div>
        <p>Рубрика: {{ bb.rubric.name }}</p>
        <h2>{{ bb.title }}</h2>
        <p>Цена: {{ bb.price }}</p>
        <p>{{ bb.content }}</p>
        <p>Дата публикации</p>
        <p>{{ bb.published|date:"d.m.Y" }}</p>
    </div>

{% endblock %}

bboard/templates/bboard/bb_form.html
{% extends "layout/basic.html" %}
{% block title %}Редактирование объявления{% endblock %}

{% block content %}
<h2>Исправление объявления</h2>

<form method="post">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {% if form.non_field_errors %}
        <ul>
            {% for error in form.non_field_errors %}
            <li><em>{{ error|escape }}</em></li>
            {% endfor %}
        </ul>
    {% endif %}
{% for field in form.visible_fields %}
{% if field.errors %}
<ul>
    {% for error in field.errors %}
    <li><em>{{ error|escape }}</em></li>
    {% endfor %}
</ul>
{% endif %}
<p>{{ field.label_tag }}<br>{{ field }}<br>
{{ field.help_text }}
</p>
{% endfor %}
    <input type="submit" value="Сохранить">
</form>

{#<form method="post">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <input type="submit" value="Сохранить">#}
{#</form>#}
{#<p></p><p></p><p></p><p></p><p></p><p></p>#}
{##}
{##}
{#<form method="post">#}
{#    {% csrf_token %}#}
{#    <ul>#}
{#    {{ form.as_ul }}#}
{#    </ul>#}
{#    <input type="submit" value="Сохранить">#}
{#</form>#}
{##}
{#<form method="post">#}
{#    {% csrf_token %}#}
{#    <table>#}
{#    {{ form }}#}
{#    </table>#}
{#    <input type="submit" value="Сохранить">#}
{#</form>#}
{% endblock %}

bboard/templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}
{% block title %}{{ current_rubric.name }}{% endblock %}

{% block content %}

<h2>Рубрика: {{ current_rubric.name }}</h2>


{% for bb in bbs %}
<div>
        <h2><a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
        <p>Цена: {{ bb.price }}</p>
        <p>{{ bb.content|truncatechars:100 }}</p>
        <p>{{ bb.published|date:"d.E.Y H:i:s z e r U T" }} назад</p>
        <p> <a href="{% url 'bboard:edit' pk=bb.pk %}">Редактировать</a></p>
        <p> <a href="{% url 'bboard:delete' pk=bb.pk %}">Удалить</a></p>
    </div>
{% endfor %}
        <div>
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">&lt</a>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        {% endif %}
    Часть№{{ page.number }} из {{ page.paginator.num_pages }}
    {% if page.has_next %}
    &nbsp;&nbsp;|&nbsp;&nbsp;
        <a href="?page={{ page.next_page_number }}">&gt</a>
    {% endif %}
    </div>
{% endblock %}
</body>
</html>

bboard/templates/bboard/create.html
{% extends "layout/basic.html" %}
{% block title %}Добавление объявления{% endblock %}

{% block content %}
<h2>Добавление объявления</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить">
</form>
{% endblock %}

bboard/templates/bboard/index.html
{% extends "layout/basic.html" %}
{% block content %}

{% for bb in bbs %}

    <div>
        <h2><a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
        <p>Цена: {{ bb.price }}</p>
        <p>{{ bb.content|truncatechars:100 }}</p>
        <p><a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">{{ bb.rubric.name }}</a></p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
       <p> <a href="{% url 'bboard:edit' pk=bb.pk %}">Редактировать</a></p>
        <p> <a href="{% url 'bboard:delete' pk=bb.pk %}">Удалить</a></p>
    <p>{{ block.super }}</p>





    </div>
{% endfor %}
    <div>
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">&lt</a>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        {% endif %}
    Часть№{{ page.number }} из {{ page.paginator.num_pages }}
    {% if page.has_next %}
    &nbsp;&nbsp;|&nbsp;&nbsp;
        <a href="?page={{ page.next_page_number }}">&gt</a>
    {% endif %}
    </div>
{% endblock %}

bboard/templates/bboard/nologin.html
{% extends "layout/basic.html" %}
{% block content %}


    <div>
        <h1>ВЫ НЕАВТОРИЗОВАНЫ!</h1>

    </div>

{% endblock %}